### PR TITLE
Drop python 3.7 support

### PR DESCRIPTION
**Pull request by thehomebrewnerd**

### CODE REVIEW

**Review by gsheni — APPROVED** [review]
assuming tests pass

**Comment by thehomebrewnerd** [comment]
> assuming tests pass

Bad assumption

**Comment by gsheni** [comment]
What if we require pyarrow for Compose (or maybe just the unit tests)?

**Comment by thehomebrewnerd** [comment]
> What if we require pyarrow for Compose (or maybe just the unit tests)?

I think it might be something else - I found found some posts indicating that upgrading to numpy 1.22 could fix this error, but I think we are constrained from doing this by other dependency requirements.

**Pull request closed without merging**
